apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspirely-app-frontend
  labels:
    app: aspirely-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspirely-app-frontend
  template:
    metadata:
      labels:
        app: aspirely-app-frontend
    spec:
      containers:
        - name: aspirely-app-frontend
          image: ghcr.io/aspirelyvn/aspirely.app.frontend:latest
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.aspirely.edu.vn"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret
